title: WarsawJS
description: We talk about JavaScript. Every month in Warsaw, Poland.
keywords: javascript, warsaw, meetup, workshop, community
url: 'https://warsawjs.com'

safe: false
encoding: 'utf-8'
plugins_dir: ./_plugins/
permalink: none

sass:
  sass_dir: assets/styles/
  style: compressed

gems:
  - jekyll-redirect-from
